# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('cellphone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=120)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
