# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselist',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='houselist',
            name='refinedDetail',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
